/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package RECEPTIONIST;

import DB.Connector;
import MAIN.Main_Menu;
import PATIENT.AddPatient;
import PATIENT.DeletePatient;
import PATIENT.UpdatePatient;
import PATIENT.ViewPatient;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author surap
 */
public class Receptionist_Activity extends javax.swing.JFrame {
public static String username;
    PreparedStatement ps = null;
    ResultSet rs = null;
    Connection connection = null;
    /**
     * Creates new form Receptionist_Activity
     */
    public Receptionist_Activity() {
        initComponents();
        Pasien.setVisible(false);
        UbahPassword.setVisible(false);
        
    }
    String active = "dashboard";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        panel_pasien = new javax.swing.JPanel();
        label_pasien = new javax.swing.JLabel();
        panel_halaman_utama = new javax.swing.JPanel();
        label_halaman_utama = new javax.swing.JLabel();
        panel_ubah_password = new javax.swing.JPanel();
        label_ubah_password = new javax.swing.JLabel();
        Mainbar = new javax.swing.JPanel();
        HalamanUtama = new javax.swing.JPanel();
        aturjanji = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        listjanji = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Pasien = new javax.swing.JPanel();
        addpasien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        updatepasien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deletepasien = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        viewpasien = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        UbahPassword = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();
        txtnewpass = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        txtconfirmpass = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnubah = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main.setBackground(new java.awt.Color(177, 205, 166));
        Main.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MainMouseEntered(evt);
            }
        });
        Main.setLayout(null);

        Sidebar.setBackground(new java.awt.Color(101, 145, 106));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_pasien.setBackground(new java.awt.Color(101, 145, 106));
        panel_pasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_pasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_pasienMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_pasienMousePressed(evt);
            }
        });

        label_pasien.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_pasien.setForeground(new java.awt.Color(204, 255, 204));
        label_pasien.setText("Pasien");

        javax.swing.GroupLayout panel_pasienLayout = new javax.swing.GroupLayout(panel_pasien);
        panel_pasien.setLayout(panel_pasienLayout);
        panel_pasienLayout.setHorizontalGroup(
            panel_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pasienLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(label_pasien)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        panel_pasienLayout.setVerticalGroup(
            panel_pasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_pasienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_pasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sidebar.add(panel_pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 290, 50));

        panel_halaman_utama.setBackground(new java.awt.Color(113, 165, 93));
        panel_halaman_utama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMousePressed(evt);
            }
        });

        label_halaman_utama.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_halaman_utama.setForeground(new java.awt.Color(255, 255, 255));
        label_halaman_utama.setText("Halaman Utama");

        javax.swing.GroupLayout panel_halaman_utamaLayout = new javax.swing.GroupLayout(panel_halaman_utama);
        panel_halaman_utama.setLayout(panel_halaman_utamaLayout);
        panel_halaman_utamaLayout.setHorizontalGroup(
            panel_halaman_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_halaman_utamaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(label_halaman_utama, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        panel_halaman_utamaLayout.setVerticalGroup(
            panel_halaman_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_halaman_utamaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_halaman_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sidebar.add(panel_halaman_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 290, 50));

        panel_ubah_password.setBackground(new java.awt.Color(101, 145, 106));
        panel_ubah_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMousePressed(evt);
            }
        });

        label_ubah_password.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_ubah_password.setForeground(new java.awt.Color(204, 255, 204));
        label_ubah_password.setText("Ubah Password");

        javax.swing.GroupLayout panel_ubah_passwordLayout = new javax.swing.GroupLayout(panel_ubah_password);
        panel_ubah_password.setLayout(panel_ubah_passwordLayout);
        panel_ubah_passwordLayout.setHorizontalGroup(
            panel_ubah_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ubah_passwordLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(label_ubah_password)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panel_ubah_passwordLayout.setVerticalGroup(
            panel_ubah_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ubah_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ubah_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sidebar.add(panel_ubah_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 290, 50));

        Main.add(Sidebar);
        Sidebar.setBounds(0, 0, 290, 770);

        Mainbar.setBackground(new java.awt.Color(102, 102, 102));
        Mainbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        HalamanUtama.setBackground(new java.awt.Color(246, 255, 233));

        aturjanji.setBackground(new java.awt.Color(101, 145, 106));
        aturjanji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aturjanjiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aturjanjiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aturjanjiMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/calendar_plus_80px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Atur Janji");

        javax.swing.GroupLayout aturjanjiLayout = new javax.swing.GroupLayout(aturjanji);
        aturjanji.setLayout(aturjanjiLayout);
        aturjanjiLayout.setHorizontalGroup(
            aturjanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aturjanjiLayout.createSequentialGroup()
                .addGroup(aturjanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aturjanjiLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aturjanjiLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel5)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        aturjanjiLayout.setVerticalGroup(
            aturjanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(aturjanjiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        listjanji.setBackground(new java.awt.Color(101, 145, 106));
        listjanji.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listjanjiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                listjanjiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                listjanjiMouseExited(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/calendar_80px.png"))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("List Janji");

        javax.swing.GroupLayout listjanjiLayout = new javax.swing.GroupLayout(listjanji);
        listjanji.setLayout(listjanjiLayout);
        listjanjiLayout.setHorizontalGroup(
            listjanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listjanjiLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listjanjiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        listjanjiLayout.setVerticalGroup(
            listjanjiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listjanjiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel18)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HalamanUtamaLayout = new javax.swing.GroupLayout(HalamanUtama);
        HalamanUtama.setLayout(HalamanUtamaLayout);
        HalamanUtamaLayout.setHorizontalGroup(
            HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanUtamaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(aturjanji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(111, 111, 111)
                .addComponent(listjanji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(607, 607, 607))
        );
        HalamanUtamaLayout.setVerticalGroup(
            HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HalamanUtamaLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(HalamanUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(listjanji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aturjanji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(475, Short.MAX_VALUE))
        );

        Mainbar.add(HalamanUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        Pasien.setBackground(new java.awt.Color(246, 255, 233));

        addpasien.setBackground(new java.awt.Color(101, 145, 106));
        addpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addpasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addpasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addpasienMouseExited(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/add_user_52px.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tambah Pasien");

        javax.swing.GroupLayout addpasienLayout = new javax.swing.GroupLayout(addpasien);
        addpasien.setLayout(addpasienLayout);
        addpasienLayout.setHorizontalGroup(
            addpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addpasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(37, 37, 37))
            .addGroup(addpasienLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addpasienLayout.setVerticalGroup(
            addpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpasienLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        updatepasien.setBackground(new java.awt.Color(101, 145, 106));
        updatepasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updatepasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updatepasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updatepasienMouseExited(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/edit_user_52px.png"))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ubah Pasien");

        javax.swing.GroupLayout updatepasienLayout = new javax.swing.GroupLayout(updatepasien);
        updatepasien.setLayout(updatepasienLayout);
        updatepasienLayout.setHorizontalGroup(
            updatepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepasienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(updatepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepasienLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updatepasienLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42))))
        );
        updatepasienLayout.setVerticalGroup(
            updatepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatepasienLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        deletepasien.setBackground(new java.awt.Color(101, 145, 106));
        deletepasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deletepasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deletepasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deletepasienMouseExited(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/remove_user_52px.png"))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hapus Pasien");

        javax.swing.GroupLayout deletepasienLayout = new javax.swing.GroupLayout(deletepasien);
        deletepasien.setLayout(deletepasienLayout);
        deletepasienLayout.setHorizontalGroup(
            deletepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepasienLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(deletepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepasienLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deletepasienLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))))
        );
        deletepasienLayout.setVerticalGroup(
            deletepasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deletepasienLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        viewpasien.setBackground(new java.awt.Color(101, 145, 106));
        viewpasien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewpasienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewpasienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewpasienMouseExited(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/groups_52px.png"))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Data Pasien");

        javax.swing.GroupLayout viewpasienLayout = new javax.swing.GroupLayout(viewpasien);
        viewpasien.setLayout(viewpasienLayout);
        viewpasienLayout.setHorizontalGroup(
            viewpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewpasienLayout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addGroup(viewpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewpasienLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel13))
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        viewpasienLayout.setVerticalGroup(
            viewpasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewpasienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PasienLayout = new javax.swing.GroupLayout(Pasien);
        Pasien.setLayout(PasienLayout);
        PasienLayout.setHorizontalGroup(
            PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PasienLayout.createSequentialGroup()
                .addContainerGap(270, Short.MAX_VALUE)
                .addGroup(PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addpasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deletepasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(312, 312, 312)
                .addGroup(PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(updatepasien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(226, 226, 226))
        );
        PasienLayout.setVerticalGroup(
            PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PasienLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatepasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(PasienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deletepasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewpasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        Mainbar.add(Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        UbahPassword.setBackground(new java.awt.Color(246, 255, 233));

        jLabel14.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(113, 165, 93));
        jLabel14.setText("Old Password");

        txtoldpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(113, 165, 93));
        jLabel15.setText("New Password");

        txtnewpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(113, 165, 93));
        jLabel16.setText("Confirm Password");

        txtconfirmpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("COCOMAT", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        btnubah.setBackground(new java.awt.Color(113, 165, 93));
        btnubah.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        btnubah.setForeground(new java.awt.Color(51, 51, 51));
        btnubah.setText("UBAH");
        btnubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnubahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UbahPasswordLayout = new javax.swing.GroupLayout(UbahPassword);
        UbahPassword.setLayout(UbahPasswordLayout);
        UbahPasswordLayout.setHorizontalGroup(
            UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UbahPasswordLayout.createSequentialGroup()
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UbahPasswordLayout.createSequentialGroup()
                                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15))
                                .addGap(118, 118, 118)
                                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(UbahPasswordLayout.createSequentialGroup()
                                        .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtnewpass)))
                            .addGroup(UbahPasswordLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(513, 513, 513))
            .addGroup(UbahPasswordLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(btnubah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UbahPasswordLayout.setVerticalGroup(
            UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UbahPasswordLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(UbahPasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnubah)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        Mainbar.add(UbahPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        Main.add(Mainbar);
        Mainbar.setBounds(290, 100, 1260, 670);

        jLabel3.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SELAMAT DATANG");
        Main.add(jLabel3);
        jLabel3.setBounds(320, 30, 225, 40);

        lblUser.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("USER");
        Main.add(lblUser);
        lblUser.setBounds(560, 30, 90, 40);

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(45, 45, 45));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/exit_26px.png"))); // NOI18N
        Logout.setText(" KELUAR");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Main.add(Logout);
        Logout.setBounds(1400, 30, 130, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_pasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_pasienMouseEntered
  
    }//GEN-LAST:event_panel_pasienMouseEntered

    private void panel_pasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_pasienMouseExited

        
    }//GEN-LAST:event_panel_pasienMouseExited

    private void panel_pasienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_pasienMousePressed
        active = "login";
        Pasien.setVisible(true);
        panel_pasien.setBackground(new Color(113,165,93));
        label_pasien.setForeground(new Color(255,255,255));
        panel_halaman_utama.setBackground(new Color(101,145,106));
        label_halaman_utama.setForeground(new Color(204,255,204));
        panel_ubah_password.setBackground(new Color(101,145,106));
        label_ubah_password.setForeground(new Color(204,255,204));
        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(Pasien);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_pasienMousePressed

    private void panel_halaman_utamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMouseEntered

    }//GEN-LAST:event_panel_halaman_utamaMouseEntered

    private void panel_halaman_utamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMouseExited

    }//GEN-LAST:event_panel_halaman_utamaMouseExited

    private void panel_halaman_utamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMousePressed
        HalamanUtama.setVisible(true);
        active = "login1";
        panel_halaman_utama.setBackground(new Color(113,165,93));
        label_halaman_utama.setForeground(new Color(255,255,255));
        panel_pasien.setBackground(new Color(101,145,106));
        label_pasien.setForeground(new Color(204,255,204));
                panel_ubah_password.setBackground(new Color(101,145,106));
        label_ubah_password.setForeground(new Color(204,255,204));

        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(HalamanUtama);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_halaman_utamaMousePressed

    private void MainMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseEntered
lblUser.setText(username.toUpperCase());
    }//GEN-LAST:event_MainMouseEntered

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Main_Menu MM = new Main_Menu();
        MM.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    private void aturjanjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aturjanjiMouseClicked
        Choose_Doctor CD = new Choose_Doctor();
        CD.setVisible(true);
        dispose();
    }//GEN-LAST:event_aturjanjiMouseClicked

    private void aturjanjiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aturjanjiMouseEntered
        aturjanji.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_aturjanjiMouseEntered

    private void aturjanjiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aturjanjiMouseExited
        aturjanji.setBackground(new Color(101,145,106));         // TODO add your handling code here:
    }//GEN-LAST:event_aturjanjiMouseExited

    private void addpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpasienMouseClicked
        AddPatient_Resepsionis ap = new AddPatient_Resepsionis();
        ap.setVisible(true);
        dispose();
    }//GEN-LAST:event_addpasienMouseClicked

    private void addpasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpasienMouseEntered
        addpasien.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_addpasienMouseEntered

    private void addpasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpasienMouseExited
        addpasien.setBackground(new Color(101,145,106));         // TODO add your handling code here:
    }//GEN-LAST:event_addpasienMouseExited

    private void updatepasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepasienMouseClicked
        UpdatePatient_Resepsionis up = new UpdatePatient_Resepsionis();
        up.setVisible(true);
        dispose();
    }//GEN-LAST:event_updatepasienMouseClicked

    private void updatepasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepasienMouseEntered
        updatepasien.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_updatepasienMouseEntered

    private void updatepasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updatepasienMouseExited
        updatepasien.setBackground(new Color(101,145,106));          // TODO add your handling code here:
    }//GEN-LAST:event_updatepasienMouseExited

    private void deletepasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepasienMouseClicked
        DeletePatient_Resepsionis dp = new DeletePatient_Resepsionis();
        dp.setVisible(true);
        dispose();
    }//GEN-LAST:event_deletepasienMouseClicked

    private void deletepasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepasienMouseEntered
        deletepasien.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_deletepasienMouseEntered

    private void deletepasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deletepasienMouseExited
        deletepasien.setBackground(new Color(101,145,106));          // TODO add your handling code here:
    }//GEN-LAST:event_deletepasienMouseExited

    private void viewpasienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpasienMouseClicked
        ViewPatient_Resepsionis vp = new ViewPatient_Resepsionis();
        vp.setVisible(true);
        dispose();
    }//GEN-LAST:event_viewpasienMouseClicked

    private void viewpasienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpasienMouseEntered
        viewpasien.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_viewpasienMouseEntered

    private void viewpasienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewpasienMouseExited
        viewpasien.setBackground(new Color(101,145,106));
    }//GEN-LAST:event_viewpasienMouseExited

    private void panel_ubah_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ubah_passwordMouseEntered

    private void panel_ubah_passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_ubah_passwordMouseExited

    private void panel_ubah_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMousePressed
UbahPassword.setVisible(true);
        panel_ubah_password.setBackground(new Color(113,165,93));
        label_ubah_password.setForeground(new Color(255,255,255));
        panel_halaman_utama.setBackground(new Color(101,145,106));
        label_halaman_utama.setForeground(new Color(204,255,204));
        panel_pasien.setBackground(new Color(101,145,106));
        label_pasien.setForeground(new Color(204,255,204));

        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(UbahPassword);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_ubah_passwordMousePressed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean cb = jCheckBox1.isSelected();
        if (cb == true ) {
            txtoldpass.setEchoChar((char) 0);
            txtnewpass.setEchoChar((char) 0);
            txtconfirmpass.setEchoChar((char) 0);
        } else {
            txtoldpass.setEchoChar('*');
            txtnewpass.setEchoChar('*');
            txtconfirmpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void btnubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnubahActionPerformed
        String pass = String.valueOf(txtnewpass.getPassword());
        String oldpass = String.valueOf(txtoldpass.getPassword());
        connection = Connector.ConnectDb();
        if (!txtnewpass.getText().equals(txtconfirmpass.getText())) {
            JOptionPane.showMessageDialog(null, "Kedua Password Harus Sama!", "Information",
                JOptionPane.INFORMATION_MESSAGE);
            txtoldpass.setText(null);
            txtnewpass.setText(null);
            txtconfirmpass.setText(null);
        } else {
            try {
                String sql = "select username, password from tbl_resepsionis where username='" + username + "'";
                ps = connection.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.first();
                if (oldpass.equals(rs.getString("password"))) {

                    try {
                        sql = "UPDATE tbl_resepsionis SET password = ? WHERE username = '"+username+"'";
                        ps = connection.prepareStatement(sql);
                        ps.setString(1, pass);

                        int rs = ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Password Berhasil Diubah");
                    } catch (Exception e) {
                        System.out.println("Error " + e.getMessage());
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Password Salah");
                    txtoldpass.setText(null);
                    txtnewpass.setText(null);
                    txtconfirmpass.setText(null);

                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Password Salah");
                txtoldpass.setText(null);
                txtnewpass.setText(null);
                txtconfirmpass.setText(null);
            }
        }
    }//GEN-LAST:event_btnubahActionPerformed

    private void listjanjiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listjanjiMouseClicked
      ViewAppointment AD = new ViewAppointment();
              AD.setVisible(true);
              dispose();
    }//GEN-LAST:event_listjanjiMouseClicked

    private void listjanjiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listjanjiMouseEntered
       listjanji.setBackground(new Color(113,165,93));
    }//GEN-LAST:event_listjanjiMouseEntered

    private void listjanjiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listjanjiMouseExited
      listjanji.setBackground(new Color(101,145,106));
    }//GEN-LAST:event_listjanjiMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HalamanUtama;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Mainbar;
    private javax.swing.JPanel Pasien;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel UbahPassword;
    private javax.swing.JPanel addpasien;
    private javax.swing.JPanel aturjanji;
    private javax.swing.JButton btnubah;
    private javax.swing.JPanel deletepasien;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel label_halaman_utama;
    private javax.swing.JLabel label_pasien;
    private javax.swing.JLabel label_ubah_password;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel listjanji;
    private javax.swing.JPanel panel_halaman_utama;
    private javax.swing.JPanel panel_pasien;
    private javax.swing.JPanel panel_ubah_password;
    private javax.swing.JPasswordField txtconfirmpass;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JPasswordField txtoldpass;
    private javax.swing.JPanel updatepasien;
    private javax.swing.JPanel viewpasien;
    // End of variables declaration//GEN-END:variables
}
