/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CASHIER;

import static CASHIER.UpdateCashier.ps;
import static CASHIER.UpdateCashier.sql;
import DB.Connector;
import DRUGS.AddDrugs;
import DRUGS.DeleteDrugs;
import DRUGS.UpdateDrugs;
import DRUGS.ViewDrugs;
import MAIN.Main_Menu;
import static RECEPTIONIST.Receptionist_Activity.username;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author surap
 */
public class Cashier_Activity extends javax.swing.JFrame {
    Connection connection = null;
    static Statement st;
    static ResultSet rs;
    static PreparedStatement ps;
    public static String username;

    /**
     * Creates new form Cashier_Activity
     */
    public Cashier_Activity() {
        initComponents();
        Ubah_Password.setVisible(false);
        Obat.setVisible(false);
    }
    String active = "dashboard";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Sidebar = new javax.swing.JPanel();
        panel_halaman_utama = new javax.swing.JPanel();
        label_halaman_utama = new javax.swing.JLabel();
        panel_ubah_password = new javax.swing.JPanel();
        label_ubah_password = new javax.swing.JLabel();
        panel_obat = new javax.swing.JPanel();
        label_obat = new javax.swing.JLabel();
        Mainbar = new javax.swing.JPanel();
        Halaman_Utama = new javax.swing.JPanel();
        Transaksi = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Ubah_Password = new javax.swing.JPanel();
        btnUbah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtoldpass = new javax.swing.JPasswordField();
        txtnewpass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        txtconfirmpass = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        Obat = new javax.swing.JPanel();
        view_obat = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        delete_obat = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        update_obat = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        tambah_obat = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Main.setBackground(new java.awt.Color(177, 205, 166));
        Main.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MainMouseMoved(evt);
            }
        });
        Main.setLayout(null);

        Sidebar.setBackground(new java.awt.Color(101, 145, 106));
        Sidebar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_halaman_utama.setBackground(new java.awt.Color(113, 165, 93));
        panel_halaman_utama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_halaman_utamaMousePressed(evt);
            }
        });

        label_halaman_utama.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_halaman_utama.setForeground(new java.awt.Color(255, 255, 255));
        label_halaman_utama.setText("Halaman Utama");

        javax.swing.GroupLayout panel_halaman_utamaLayout = new javax.swing.GroupLayout(panel_halaman_utama);
        panel_halaman_utama.setLayout(panel_halaman_utamaLayout);
        panel_halaman_utamaLayout.setHorizontalGroup(
            panel_halaman_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_halaman_utamaLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(label_halaman_utama)
                .addGap(38, 38, 38))
        );
        panel_halaman_utamaLayout.setVerticalGroup(
            panel_halaman_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label_halaman_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Sidebar.add(panel_halaman_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 290, 50));

        panel_ubah_password.setBackground(new java.awt.Color(101, 145, 106));
        panel_ubah_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_ubah_passwordMousePressed(evt);
            }
        });

        label_ubah_password.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_ubah_password.setForeground(new java.awt.Color(204, 255, 204));
        label_ubah_password.setText("Ubah Password");

        javax.swing.GroupLayout panel_ubah_passwordLayout = new javax.swing.GroupLayout(panel_ubah_password);
        panel_ubah_password.setLayout(panel_ubah_passwordLayout);
        panel_ubah_passwordLayout.setHorizontalGroup(
            panel_ubah_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ubah_passwordLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(label_ubah_password)
                .addGap(37, 37, 37))
        );
        panel_ubah_passwordLayout.setVerticalGroup(
            panel_ubah_passwordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_ubah_passwordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_ubah_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sidebar.add(panel_ubah_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 290, 50));

        panel_obat.setBackground(new java.awt.Color(101, 145, 106));
        panel_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_obatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_obatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_obatMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_obatMousePressed(evt);
            }
        });

        label_obat.setBackground(new java.awt.Color(101, 145, 106));
        label_obat.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        label_obat.setForeground(new java.awt.Color(204, 255, 204));
        label_obat.setText("Obat");

        javax.swing.GroupLayout panel_obatLayout = new javax.swing.GroupLayout(panel_obat);
        panel_obat.setLayout(panel_obatLayout);
        panel_obatLayout.setHorizontalGroup(
            panel_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_obatLayout.createSequentialGroup()
                .addContainerGap(106, Short.MAX_VALUE)
                .addComponent(label_obat, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        panel_obatLayout.setVerticalGroup(
            panel_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_obatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        Sidebar.add(panel_obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 290, 50));

        Main.add(Sidebar);
        Sidebar.setBounds(0, 0, 290, 770);

        Mainbar.setBackground(new java.awt.Color(102, 102, 102));
        Mainbar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Halaman_Utama.setBackground(new java.awt.Color(246, 255, 233));

        Transaksi.setBackground(new java.awt.Color(101, 145, 106));
        Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TransaksiMouseExited(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/sales_performance_50px.png"))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Transaksi");

        javax.swing.GroupLayout TransaksiLayout = new javax.swing.GroupLayout(Transaksi);
        Transaksi.setLayout(TransaksiLayout);
        TransaksiLayout.setHorizontalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        TransaksiLayout.setVerticalGroup(
            TransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TransaksiLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Halaman_UtamaLayout = new javax.swing.GroupLayout(Halaman_Utama);
        Halaman_Utama.setLayout(Halaman_UtamaLayout);
        Halaman_UtamaLayout.setHorizontalGroup(
            Halaman_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Halaman_UtamaLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(Transaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(959, 959, 959))
        );
        Halaman_UtamaLayout.setVerticalGroup(
            Halaman_UtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Halaman_UtamaLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(Transaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(465, Short.MAX_VALUE))
        );

        Mainbar.add(Halaman_Utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        Ubah_Password.setBackground(new java.awt.Color(246, 255, 233));

        btnUbah.setBackground(new java.awt.Color(113, 165, 93));
        btnUbah.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        btnUbah.setForeground(new java.awt.Color(51, 51, 51));
        btnUbah.setText("UBAH");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(113, 165, 93));
        jLabel2.setText("Old Password");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(113, 165, 93));
        jLabel6.setText("New Password");

        txtoldpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        txtnewpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(113, 165, 93));
        jLabel7.setText("Confirm Password");

        txtconfirmpass.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jCheckBox1.setFont(new java.awt.Font("COCOMAT", 1, 12)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(51, 51, 51));
        jCheckBox1.setText("Show Password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Ubah_PasswordLayout = new javax.swing.GroupLayout(Ubah_Password);
        Ubah_Password.setLayout(Ubah_PasswordLayout);
        Ubah_PasswordLayout.setHorizontalGroup(
            Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ubah_PasswordLayout.createSequentialGroup()
                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBox1))
                    .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))
                                .addGap(118, 118, 118)
                                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                                        .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtnewpass)))
                            .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(513, 513, 513))
            .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                .addGap(406, 406, 406)
                .addComponent(btnUbah)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Ubah_PasswordLayout.setVerticalGroup(
            Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ubah_PasswordLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtoldpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnewpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(Ubah_PasswordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtconfirmpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnUbah)
                .addContainerGap(187, Short.MAX_VALUE))
        );

        Mainbar.add(Ubah_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        Obat.setBackground(new java.awt.Color(246, 255, 233));

        view_obat.setBackground(new java.awt.Color(101, 145, 106));
        view_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                view_obatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                view_obatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                view_obatMouseExited(evt);
            }
        });

        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/15.png"))); // NOI18N

        jLabel37.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Data Obat");

        javax.swing.GroupLayout view_obatLayout = new javax.swing.GroupLayout(view_obat);
        view_obat.setLayout(view_obatLayout);
        view_obatLayout.setHorizontalGroup(
            view_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, view_obatLayout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(view_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37))
                .addGap(58, 58, 58))
        );
        view_obatLayout.setVerticalGroup(
            view_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(view_obatLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel37)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        delete_obat.setBackground(new java.awt.Color(101, 145, 106));
        delete_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                delete_obatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_obatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delete_obatMouseExited(evt);
            }
        });

        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/13.png"))); // NOI18N

        jLabel39.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Hapus Obat");

        javax.swing.GroupLayout delete_obatLayout = new javax.swing.GroupLayout(delete_obat);
        delete_obat.setLayout(delete_obatLayout);
        delete_obatLayout.setHorizontalGroup(
            delete_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_obatLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(delete_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_obatLayout.createSequentialGroup()
                        .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, delete_obatLayout.createSequentialGroup()
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        delete_obatLayout.setVerticalGroup(
            delete_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delete_obatLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel39)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        update_obat.setBackground(new java.awt.Color(101, 145, 106));
        update_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update_obatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                update_obatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                update_obatMouseExited(evt);
            }
        });

        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/12.png"))); // NOI18N

        jLabel41.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Ubah Obat");

        javax.swing.GroupLayout update_obatLayout = new javax.swing.GroupLayout(update_obat);
        update_obat.setLayout(update_obatLayout);
        update_obatLayout.setHorizontalGroup(
            update_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_obatLayout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(update_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_obatLayout.createSequentialGroup()
                        .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, update_obatLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addGap(54, 54, 54))))
        );
        update_obatLayout.setVerticalGroup(
            update_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_obatLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel40, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel41)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        tambah_obat.setBackground(new java.awt.Color(101, 145, 106));
        tambah_obat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tambah_obatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tambah_obatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tambah_obatMouseExited(evt);
            }
        });

        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/pill11_52px.png"))); // NOI18N

        jLabel43.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(255, 255, 255));
        jLabel43.setText("Tambah Obat");

        javax.swing.GroupLayout tambah_obatLayout = new javax.swing.GroupLayout(tambah_obat);
        tambah_obat.setLayout(tambah_obatLayout);
        tambah_obatLayout.setHorizontalGroup(
            tambah_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_obatLayout.createSequentialGroup()
                .addGroup(tambah_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tambah_obatLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tambah_obatLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel43)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tambah_obatLayout.setVerticalGroup(
            tambah_obatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tambah_obatLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel43)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ObatLayout = new javax.swing.GroupLayout(Obat);
        Obat.setLayout(ObatLayout);
        ObatLayout.setHorizontalGroup(
            ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ObatLayout.createSequentialGroup()
                .addContainerGap(273, Short.MAX_VALUE)
                .addGroup(ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tambah_obat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(delete_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(303, 303, 303)
                .addGroup(ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(226, 226, 226))
        );
        ObatLayout.setVerticalGroup(
            ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ObatLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tambah_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88)
                .addGroup(ObatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delete_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(view_obat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        Mainbar.add(Obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 730));

        Main.add(Mainbar);
        Mainbar.setBounds(290, 100, 1260, 670);

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELAMAT DATANG");
        Main.add(jLabel1);
        jLabel1.setBounds(320, 30, 225, 30);

        lblUser.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        lblUser.setForeground(new java.awt.Color(255, 255, 255));
        lblUser.setText("USER");
        Main.add(lblUser);
        lblUser.setBounds(570, 30, 150, 30);

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setFont(new java.awt.Font("Ink Free", 0, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(45, 45, 45));
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICON/exit_26px.png"))); // NOI18N
        Logout.setText(" KELUAR");
        Logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Main.add(Logout);
        Logout.setBounds(1390, 20, 140, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, 1550, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 769, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_halaman_utamaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMouseEntered

    }//GEN-LAST:event_panel_halaman_utamaMouseEntered

    private void panel_halaman_utamaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMouseExited

    }//GEN-LAST:event_panel_halaman_utamaMouseExited

    private void panel_halaman_utamaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_halaman_utamaMousePressed
        active = "dashboard";

        Halaman_Utama.setVisible(true);
        panel_halaman_utama.setBackground(new Color(113, 165, 93));
        label_halaman_utama.setForeground(new Color(255, 255, 255));
        panel_ubah_password.setBackground(new Color(101, 145, 106));
        label_ubah_password.setForeground(new Color(204, 255, 204));
                        panel_obat.setBackground(new Color(101, 145, 106));
        label_obat.setForeground(new Color(204, 255, 204));

        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(Halaman_Utama);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_halaman_utamaMousePressed

    private void panel_ubah_passwordMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMouseEntered

    }//GEN-LAST:event_panel_ubah_passwordMouseEntered

    private void panel_ubah_passwordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMouseExited

    }//GEN-LAST:event_panel_ubah_passwordMouseExited

    private void panel_ubah_passwordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_ubah_passwordMousePressed
        Ubah_Password.setVisible(true);
        active = "ubahpassword";
        panel_ubah_password.setBackground(new Color(113, 165, 93));
        label_ubah_password.setForeground(new Color(255, 255, 255));
        panel_halaman_utama.setBackground(new Color(101, 145, 106));
        label_halaman_utama.setForeground(new Color(204, 255, 204));
                        panel_obat.setBackground(new Color(101, 145, 106));
        label_obat.setForeground(new Color(204, 255, 204));

        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(Ubah_Password);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_ubah_passwordMousePressed

    private void MainMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainMouseMoved
        lblUser.setText(username.toUpperCase());
    }//GEN-LAST:event_MainMouseMoved

    private void TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseClicked
        Transaction Tn = new Transaction();
        Tn.setVisible(true);
        dispose();
    }//GEN-LAST:event_TransaksiMouseClicked

    private void TransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseEntered
        Transaksi.setBackground(new Color(113, 165, 93));
    }//GEN-LAST:event_TransaksiMouseEntered

    private void TransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TransaksiMouseExited
        Transaksi.setBackground(new Color(101, 145, 106));         // TODO add your handling code here:
    }//GEN-LAST:event_TransaksiMouseExited

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String pass = String.valueOf(txtnewpass.getPassword());
        String oldpass = String.valueOf(txtoldpass.getPassword());
          connection = Connector.ConnectDb();
                  if (!txtnewpass.getText().equals(txtconfirmpass.getText())) {
                    JOptionPane.showMessageDialog(null, "Kedua Password Harus Sama!", "Information",
                    JOptionPane.INFORMATION_MESSAGE);
                    txtoldpass.setText(null);
                    txtnewpass.setText(null);
                    txtconfirmpass.setText(null);
                } else {        
        try {
             String sql = "select username, password from tbl_kasir where username='" + username + "'";
                ps = connection.prepareStatement(sql);
                rs = ps.executeQuery();
                rs.first();
                if (oldpass.equals(rs.getString("password"))) {

        try {
            sql = "UPDATE tbl_kasir SET password = ? WHERE username = '"+username+"'";
            ps = connection.prepareStatement(sql);
            ps.setString(1, pass);

            int rs = ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Password Berhasil Diubah");
        } catch (Exception e) {
            System.out.println("Error " + e.getMessage());
        }
                }else{
                    JOptionPane.showMessageDialog(null, "Password Salah");
                    txtoldpass.setText(null);
                    txtnewpass.setText(null);
                    txtconfirmpass.setText(null);
                }
        }catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Password Salah");
                    txtoldpass.setText(null);
                    txtnewpass.setText(null);
                    txtconfirmpass.setText(null);
                }
                  }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        boolean cb = jCheckBox1.isSelected();
        if (cb == true ) {
            txtoldpass.setEchoChar((char) 0);
            txtnewpass.setEchoChar((char) 0);
            txtconfirmpass.setEchoChar((char) 0);
        } else {
            txtoldpass.setEchoChar('*');
            txtnewpass.setEchoChar('*');
            txtconfirmpass.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void view_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_obatMouseClicked
        ViewDrugs_Cashier AD = new ViewDrugs_Cashier();
        AD.setVisible(true);
        dispose();
    }//GEN-LAST:event_view_obatMouseClicked

    private void view_obatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_obatMouseEntered
        view_obat.setBackground(new Color(113, 165, 93));
    }//GEN-LAST:event_view_obatMouseEntered

    private void view_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_view_obatMouseExited
        view_obat.setBackground(new Color(101, 145, 106));
    }//GEN-LAST:event_view_obatMouseExited

    private void delete_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_obatMouseClicked
        DeleteDrugs_Cashier AD = new DeleteDrugs_Cashier();
        AD.setVisible(true);
        dispose();
    }//GEN-LAST:event_delete_obatMouseClicked

    private void delete_obatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_obatMouseEntered
        delete_obat.setBackground(new Color(113, 165, 93));
    }//GEN-LAST:event_delete_obatMouseEntered

    private void delete_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_obatMouseExited
        delete_obat.setBackground(new Color(101, 145, 106));
    }//GEN-LAST:event_delete_obatMouseExited

    private void update_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_obatMouseClicked
        UpdateDrugs_Cashier AD = new UpdateDrugs_Cashier();
        AD.setVisible(true);
        dispose();
    }//GEN-LAST:event_update_obatMouseClicked

    private void update_obatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_obatMouseEntered
        update_obat.setBackground(new Color(113, 165, 93));
    }//GEN-LAST:event_update_obatMouseEntered

    private void update_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update_obatMouseExited
        update_obat.setBackground(new Color(101, 145, 106));
    }//GEN-LAST:event_update_obatMouseExited

    private void tambah_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_obatMouseClicked
        AddDrugs_Cashier AD = new AddDrugs_Cashier();
        AD.setVisible(true);
        dispose();
    }//GEN-LAST:event_tambah_obatMouseClicked

    private void tambah_obatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_obatMouseEntered
        tambah_obat.setBackground(new Color(113, 165, 93));
    }//GEN-LAST:event_tambah_obatMouseEntered

    private void tambah_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tambah_obatMouseExited
        tambah_obat.setBackground(new Color(101, 145, 106));
    }//GEN-LAST:event_tambah_obatMouseExited

    private void panel_obatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_obatMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_obatMouseEntered

    private void panel_obatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_obatMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_obatMouseExited

    private void panel_obatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_obatMousePressed
        Obat.setVisible(true);
        active = "obat";
        panel_obat.setBackground(new Color(113, 165, 93));
        label_obat.setForeground(new Color(255, 255, 255));
        panel_halaman_utama.setBackground(new Color(101, 145, 106));
        label_halaman_utama.setForeground(new Color(204, 255, 204));
        panel_ubah_password.setBackground(new Color(101, 145, 106));
        label_ubah_password.setForeground(new Color(204, 255, 204));

        try {
            Mainbar.removeAll();
            Mainbar.repaint();
            Mainbar.revalidate();

            Mainbar.add(Obat);
            Mainbar.repaint();
            Mainbar.revalidate();
        } catch (Exception e) {

        }
    }//GEN-LAST:event_panel_obatMousePressed

    private void panel_obatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_obatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panel_obatMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        Main_Menu MM = new Main_Menu();
        MM.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cashier_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cashier_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cashier_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cashier_Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cashier_Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Halaman_Utama;
    private javax.swing.JLabel Logout;
    private javax.swing.JPanel Main;
    private javax.swing.JPanel Mainbar;
    private javax.swing.JPanel Obat;
    private javax.swing.JPanel Sidebar;
    private javax.swing.JPanel Transaksi;
    private javax.swing.JPanel Ubah_Password;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel delete_obat;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel label_halaman_utama;
    private javax.swing.JLabel label_obat;
    private javax.swing.JLabel label_ubah_password;
    private javax.swing.JLabel lblUser;
    private javax.swing.JPanel panel_halaman_utama;
    private javax.swing.JPanel panel_obat;
    private javax.swing.JPanel panel_ubah_password;
    private javax.swing.JPanel tambah_obat;
    private javax.swing.JPasswordField txtconfirmpass;
    private javax.swing.JPasswordField txtnewpass;
    private javax.swing.JPasswordField txtoldpass;
    private javax.swing.JPanel update_obat;
    private javax.swing.JPanel view_obat;
    // End of variables declaration//GEN-END:variables
}
